### ISSUE TITLE
implement blockquote in html

### ISSUE THREAD

**Issue by alloygodwin1** [alloyyokesh/Testapp#12]

**Comment by alloygodwin1** [comment]
use this real time html editor for single page html tasks

https://htmledit.squarefree.com/

**Comment by alloyyokesh** [comment]
Submitted

**Comment by alloygodwin1** [comment]
<br> tag should not have any close tag

**Comment by alloygodwin1** [comment]
<br> or <br />

**Comment by alloyyokesh** [comment]
Updated  the changes please retest
